# Generated by Django 5.2.6 on 2025-09-25 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examquestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiologySubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic', to='examquestions.biologytopic')),
            ],
        ),
        migrations.CreateModel(
            name='BiologySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='examquestions.biologysubtopic')),
            ],
        ),
    ]
