# Generated by Django 5.2.6 on 2025-09-25 15:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examquestions', '0002_biologysubtopic_biologysubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biologysubcategory',
            options={'ordering': ['subtopic__topic__topic', 'subtopic__title', 'title']},
        ),
        migrations.AlterModelOptions(
            name='biologysubtopic',
            options={'ordering': ['topic__topic', 'title']},
        ),
        migrations.AlterModelOptions(
            name='biologytopic',
            options={'ordering': ['topic']},
        ),
        migrations.AlterModelOptions(
            name='questionsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='biologysubtopic',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='biologysubtopic',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='examquestions.biologytopic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionsession',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examquestions.biologysubcategory'),
        ),
        migrations.AddField(
            model_name='questionsession',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examquestions.biologysubtopic'),
        ),
        migrations.AlterField(
            model_name='biologytopic',
            name='topic',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionsession',
            name='number_of_questions',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='questionsession',
            name='total_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionsession',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='biologysubcategory',
            constraint=models.UniqueConstraint(fields=('subtopic', 'title'), name='uniq_subcategory_per_subtopic'),
        ),
        migrations.AddConstraint(
            model_name='biologysubtopic',
            constraint=models.UniqueConstraint(fields=('topic', 'title'), name='uniq_subtopic_per_topic'),
        ),
    ]
