# Generated by Django 5.2.6 on 2025-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examquestions", "0003_alter_biologysubcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biologysubcategory",
            options={
                "ordering": [
                    "subtopic__topic__exam_board",
                    "subtopic__topic__topic",
                    "subtopic__title",
                    "title",
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="biologysubtopic",
            options={"ordering": ["topic__exam_board", "topic__topic", "title"]},
        ),
        migrations.AlterModelOptions(
            name="biologytopic", options={"ordering": ["exam_board", "topic"]},
        ),
        migrations.AddField(
            model_name="biologytopic",
            name="exam_board",
            field=models.CharField(
                choices=[("OCR", "OCR"), ("AQA", "AQA")],
                db_index=True,
                default="OCR",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="biologytopic",
            name="topic",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="biologytopic",
            constraint=models.UniqueConstraint(
                fields=("topic", "exam_board"), name="uniq_topic_per_exam_board"
            ),
        ),
    ]
