# Generated by Django 5.2.6 on 2026-04-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examquestions', '0009_questionsession_soft_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcsesciencesubcategory',
            options={'ordering': ['subtopic__topic__exam_board', 'subtopic__topic__subject', 'subtopic__topic__tier', 'subtopic__topic__topic', 'subtopic__title', 'title']},
        ),
        migrations.AlterModelOptions(
            name='gcsesciencesubtopic',
            options={'ordering': ['topic__exam_board', 'topic__subject', 'topic__tier', 'topic__topic', 'title']},
        ),
        migrations.AlterModelOptions(
            name='gcsesciencetopic',
            options={'ordering': ['exam_board', 'subject', 'tier', 'topic']},
        ),
        migrations.AlterField(
            model_name='gcsesciencetopic',
            name='subject',
            field=models.CharField(choices=[('BIOLOGY', 'Biology'), ('CHEMISTRY', 'Chemistry'), ('PHYSICS', 'Physics'), ('COMBINED', 'Combined Science')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='questionsession',
            name='gcse_subject',
            field=models.CharField(blank=True, choices=[('BIOLOGY', 'Biology'), ('CHEMISTRY', 'Chemistry'), ('PHYSICS', 'Physics'), ('COMBINED', 'Combined Science')], max_length=16),
        ),
    ]
