# Generated by Django 5.2.6 on 2026-04-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examquestions', '0011_questionsession_science_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biologytopic',
            options={'ordering': ['exam_board', 'specification', 'topic']},
        ),
        migrations.AlterModelOptions(
            name='gcsesciencetopic',
            options={'ordering': ['exam_board', 'specification', 'subject', 'tier', 'topic']},
        ),
        migrations.RemoveConstraint(
            model_name='biologytopic',
            name='uniq_topic_per_exam_board',
        ),
        migrations.RemoveConstraint(
            model_name='gcsesciencetopic',
            name='uniq_gcse_topic_per_board_subject',
        ),
        migrations.AddField(
            model_name='biologytopic',
            name='specification',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gcsesciencetopic',
            name='specification',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionsession',
            name='specification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='biologytopic',
            name='exam_board',
            field=models.CharField(choices=[('OCR', 'OCR'), ('AQA', 'AQA'), ('EDEXCEL', 'Edexcel')], db_index=True, default='OCR', max_length=8),
        ),
        migrations.AlterField(
            model_name='gcsesciencetopic',
            name='exam_board',
            field=models.CharField(choices=[('OCR', 'OCR'), ('AQA', 'AQA'), ('EDEXCEL', 'Edexcel')], db_index=True, default='OCR', max_length=8),
        ),
        migrations.AlterField(
            model_name='servedquestion',
            name='exam_board',
            field=models.CharField(choices=[('OCR', 'OCR'), ('AQA', 'AQA'), ('EDEXCEL', 'Edexcel')], db_index=True, max_length=8),
        ),
        migrations.AddConstraint(
            model_name='biologytopic',
            constraint=models.UniqueConstraint(fields=('topic', 'exam_board', 'specification'), name='uniq_topic_per_exam_board'),
        ),
        migrations.AddConstraint(
            model_name='gcsesciencetopic',
            constraint=models.UniqueConstraint(fields=('topic', 'exam_board', 'specification', 'subject', 'tier'), name='uniq_gcse_topic_per_board_subject'),
        ),
    ]
